### ISSUE TITLE
Crew Data download from Wiki

### ISSUE THREAD

**Issue by phate2004** [augustenz/STT-Collection-Manager#1]
I noticed that the URL set to the crew page is not correct anymore.
correct link would be: https://stt.wiki/wiki/Crew/List?action=raw

**Comment by augustenz** [comment]
Hi phate, thanks for noticing and reporting!

I just uploaded an updated version with the new URL.
Should it change again in the future (and until the code is updated with any new URL), in version 1.2 of the program all URLs can be changed from the settings tab.

Cheers!
